### PR TITLE
Clean up management of strings v bytes.

### LINKED ISSUE #19: pitivi fails to build with itstool/py3
I switched our itstool package over to be py3 based - and most things work (after a few hiccups)

One package constantly failing is pitivi, which fails with an error like this:

```
[   79s] [4/220] /usr/bin/itstool -m help/cs/cs.mo ../help/cs/../C/about.page --output help/cs/about.page
[   79s] FAILED: help/cs/about.page 
[   79s] /usr/bin/itstool -m help/cs/cs.mo ../help/cs/../C/about.page --output help/cs/about.page
[   79s] Traceback (most recent call last):
[   79s]   File "/usr/bin/itstool", line 1605, in <module>
[   79s]     fout.write(serialized)
[   79s] TypeError: write() argument must be str, not bytes
[   79s] [5/220] /usr/bin/itstool -m help/de/de.mo ../help/de/../C/about.page --output help/de/about.page
[   79s] FAILED: help/de/about.page 
[   79s] /usr/bin/itstool -m help/de/de.mo ../help/de/../C/about.page --output help/de/about.page
[   79s] Traceback (most recent call last):
[   79s]   File "/usr/bin/itstool", line 1605, in <module>
[   79s]     fout.write(serialized)
[   79s] TypeError: write() argument must be str, not bytes
```

Interestingly enough, just a couple lines before the error reported, itstool does this:

```
            if PY3:
                # For some reason, under py3, our serialized data is returns as a str.
                # Let's encode it to bytes
                serialized = serialized.encode('utf-8')
```

Skipping the encode works for cs merge, but fails on other languages

### PR DESCRIPTION
**Pull request by mcepl**
I don't think it is a good idea to mix open() and io.open() (they are not the same thing in Python 2).

Fixes #19.

### CODE REVIEW

**Comment by mcepl** [comment]
Hmm, there is something seriously wrong with my patch https://build.opensuse.org/package/live_build_log/home:mcepl:work/pitivi/openSUSE_Tumbleweed/i586 ... it seems to somehow screw up ``*.mo`` files.

**Comment by shaunix** [comment]
This looks a lot cleaner, and I like that it's using `with` to wrap code using opened files. I plan on dropping python2 support in the next itstool version. From what I'm seeing on the internet, it seems like `open` is `io.open` in python3, and so we can just use `open` for python3-only code.

**Comment by mcepl** [comment]
> This looks a lot cleaner, and I like that it's using `with` to wrap code using opened files. I plan on dropping python2 support in the next itstool version. From what I'm seeing on the internet, it seems like `open` is `io.open` in python3, and so we can just use `open` for python3-only code.

Yes, `io.open` is the same thing as `open` in Python 3, but it really doesn’t matter and it is Py2k-compatible, so why not.

Should I rebase on the top of the current master?

**Comment by shaunix** [comment]
> Should I rebase on the top of the current master?

If you've got the time. Otherwise, I'll get to it. I plan on releasing a new version before GNOME 40 in March. I'm trying to get thru all the issues and PRs.

**Pull request closed without merging**
